name: ci

on:
  push:
    branches:
      - main
      - dev
      - 2.x
  pull_request:
    branches:
      - main
      - dev
      - 2.x

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build:all
      - uses: codecov/codecov-action@v3
