name: GHRS:ghrs
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    name: github-repo-stats
    if: github.repository == 'nutui-uniapp/nutui-uniapp'
    runs-on: ubuntu-latest
    steps:
      - name: GHRS
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: nutui-uniapp/nutui-uniapp
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
